version: '3.8'
services:
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_URI="mongodb+srv://pac-admin:pac-password@cluster0.mdu0fsz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
