name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Clone repository server folder
      run: |
        sudo rm -r Cabinet-Website \
        git clone git@github.com:Mattynb/Cabinet-Website.git -b main --single-branch \
        cd Cabinet-Website/server
    - name: Set environment variables and start server
      run: |
        export PORT=""
        export MONGO_URI=${{ secrets.MONGO_URI }}
        export JWT_SECRET=${{ secrets.JWT_SECRET }}
        export EMAIL_USER=${{ secrets.EMAIL_USER }}
        export EMAIL_PASS=${{ secrets.EMAIL_PASS }}
        npm start