name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    -name: Pull Docker Image
      run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cabinet_server:latest
    -name: Delete Old Container
      run: sudo docker rm -f cabinet_server || true
    -name: Run New Container
      run: sudo docker run -d -p 8080:8080 --name cabinet_server ${{ secrets.DOCKER_USERNAME }}/cabinet_server:latest