name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Delete Old Container
      run: sudo docker rm -f cabinet_server || true
    - name: Delete all Stopped images and containers
      run: yes | sudo docker system prune -a 
    - name: Run New Container
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        export MONGO_URI=${{ secrets.MONGO_URI }}
        export JWT_SECRET=${{ secrets.JWT_SECRET }}
        export EMAIL_USER=${{ secrets.EMAIL_USER }}
        export EMAIL_PASS=${{ secrets.EMAIL_PASS }}
        npm start