name: CICD Pipeline

on:
  push:
    branches: [ "main", "mergin_server_debug" ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ "main", "mergin_server_debug" ]
    paths:
      - 'server/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'server'
        ref: 'mergin_server_debug'  # Specify the branch name here

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'  # Set this to your project's required Node.js version

    - name: Install dependencies
      run: |
        cd server
        npm install

    - name: Start server with PM2
      run: |
        pm2 start ecosystem.config.js --env prod
        pm2 save